set_toolset("cc", "gcc-3.4")

target("boot")
    set_kind("phony")
    set_rundir("linux-0.11")
    before_build(function (target)
        os.vrun("as86 -0 -a -o linux-0.11/boot/bootsect.o linux-0.11/boot/bootsect.s")
        os.vrun("ld86 -0 -s -o linux-0.11/boot/bootsect linux-0.11/boot/bootsect.o")
        
        os.vrun("as86 -0 -a -o linux-0.11/boot/setup.o linux-0.11/boot/setup.s")
        os.vrun("ld86 -0 -s -o linux-0.11/boot/setup linux-0.11/boot/setup.o")

        os.vrun("gcc-3.4 -m32 -g -I./include -traditional -c linux-0.11/boot/head.s")
        os.vrun("mv head.o linux-0.11/boot")
    end)
    before_clean(function (target)
        os.rm("linux-0.11/boot/bootsect.o")
        os.rm("linux-0.11/boot/bootsect")
        os.rm("linux-0.11/boot/setup.o")
        os.rm("linux-0.11/boot/setup")
        os.rm("linux-0.11/boot/head.o")
    end)

target("fs")
    set_kind("object")
    set_arch("i386")
    add_includedirs("linux-0.11/include")
    add_cflags("-m32 -g -Wall -O2 -fomit-frame-pointer -nostdinc")
    add_files("linux-0.11/fs/*.c")

target("build-script")
    set_kind("binary")
    set_toolset("cc", "gcc-11")
    set_targetdir("linux-0.11/tools")
    set_filename("build")
    add_files("linux-0.11/tools/build.c")
