set_toolset("cc", "gcc-3.4")

target("boot")
    set_kind("phony")
    before_build(function (target)
        os.vrun("as86 -0 -a -o linux-0.11/boot/bootsect.o linux-0.11/boot/bootsect.s")
        os.vrun("ld86 -0 -s -o linux-0.11/boot/bootsect linux-0.11/boot/bootsect.o")
        
        os.vrun("as86 -0 -a -o linux-0.11/boot/setup.o linux-0.11/boot/setup.s")
        os.vrun("ld86 -0 -s -o linux-0.11/boot/setup linux-0.11/boot/setup.o")
    end)
    before_clean(function (target)
        os.rm("linux-0.11/boot/bootsect.o")
        os.rm("linux-0.11/boot/bootsect")
        os.rm("linux-0.11/boot/setup.o")
        os.rm("linux-0.11/boot/setup")
    end)

target("boot/head")
    set_kind("object")
    set_arch("i386")
    add_files("linux-0.11/boot/head.s")

target("init/main")
    set_kind("object")
    set_arch("i386")
    add_includedirs("linux-0.11/include")
    add_files("linux-0.11/init/main.c")

target("kernel")
    set_kind("object")
    set_arch("i386")
    add_includedirs("linux-0.11/include")
    add_cflags("-m32 -g -Wall -O -fstrength-reduce -fomit-frame-pointer -finline-functions -nostdinc")
    add_files("linux-0.11/kernel/*.s")
    add_files("linux-0.11/kernel/*.c")

target("fs")
    set_kind("object")
    set_arch("i386")
    add_includedirs("linux-0.11/include")
    add_cflags("-m32 -g -Wall -fstrength-reduce -fomit-frame-pointer -nostdinc")
    add_files("linux-0.11/fs/*.c")

target("mm")
    set_kind("object")
    set_arch("i386")
    add_includedirs("linux-0.11/include")
    add_cflags("-m32 -g -Wall -fstrength-reduce -fomit-frame-pointer -nostdinc")
    add_files("linux-0.11/mm/*.s")
    add_files("linux-0.11/mm/*.c")

target("build-script")
    set_kind("binary")
    set_toolset("cc", "gcc-11")
    set_targetdir("linux-0.11/tools")
    set_filename("build")
    add_files("linux-0.11/tools/build.c")
